project_id = "cmqbmzsjassajujsdlfg"

[functions.generate-draft]
verify_jwt = true

[functions.send-newsletter]
verify_jwt = true

[functions.sync-sources]
verify_jwt = true

[functions.scheduled-draft-generator]
verify_jwt = false

[functions.scheduled-email-sender]
verify_jwt = false